//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace JBCStationControllerSrv
{
    namespace My.Resources
    {
        using System;


        /// <summary>
        ///   A strongly-typed resource class, for looking up localized strings, etc.
        /// </summary>
        // This class was auto-generated by the StronglyTypedResourceBuilder
        // class via a tool like ResGen or Visual Studio.
        // To add or remove a member, edit your .ResX file then rerun ResGen
        // with the /str option, or rebuild your VS project.
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        internal class Resources
        {

            private static global::System.Resources.ResourceManager resourceMan;

            private static global::System.Globalization.CultureInfo resourceCulture;

            [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
            internal Resources()
            {
            }

            /// <summary>
            ///   Returns the cached ResourceManager instance used by this class.
            /// </summary>
            [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
            internal static global::System.Resources.ResourceManager ResourceManager
            {
                get
                {
                    if (object.ReferenceEquals(resourceMan, null))
                    {
                        global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JBCStationControllerSrv.Properties.Resources", typeof(Resources).Assembly);
                        resourceMan = temp;
                    }
                    return resourceMan;
                }
            }

            /// <summary>
            ///   Overrides the current thread's CurrentUICulture property for all
            ///   resource lookups using this strongly typed resource class.
            /// </summary>
            [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
            internal static global::System.Globalization.CultureInfo Culture
            {
                get
                {
                    return resourceCulture;
                }
                set
                {
                    resourceCulture = value;
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Function not supported.
            /// </summary>
            internal static string errFunctionNotSupported
            {
                get
                {
                    return ResourceManager.GetString("errFunctionNotSupported", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Not controlled error. See Detail data..
            /// </summary>
            internal static string errNotControlled
            {
                get
                {
                    return ResourceManager.GetString("errNotControlled", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Not valid tool..
            /// </summary>
            internal static string errNotValidTool
            {
                get
                {
                    return ResourceManager.GetString("errNotValidTool", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Error in service. See Detail data..
            /// </summary>
            internal static string errServiceError
            {
                get
                {
                    return ResourceManager.GetString("errServiceError", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Station not found..
            /// </summary>
            internal static string errStationNotFound
            {
                get
                {
                    return ResourceManager.GetString("errStationNotFound", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Error creating service.
            /// </summary>
            internal static string evErrorCreating
            {
                get
                {
                    return ResourceManager.GetString("evErrorCreating", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Custom Command Error.
            /// </summary>
            internal static string evErrorOnCustomCommand
            {
                get
                {
                    return ResourceManager.GetString("evErrorOnCustomCommand", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Error starting JBC Connect DLL.
            /// </summary>
            internal static string evErrorStartingDLL
            {
                get
                {
                    return ResourceManager.GetString("evErrorStartingDLL", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to New Event Service.
            /// </summary>
            internal static string evNew
            {
                get
                {
                    return ResourceManager.GetString("evNew", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Off.
            /// </summary>
            internal static string evOff
            {
                get
                {
                    return ResourceManager.GetString("evOff", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to On.
            /// </summary>
            internal static string evOn
            {
                get
                {
                    return ResourceManager.GetString("evOn", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Searching Ethernet Stations.
            /// </summary>
            internal static string evSearchingETHStations
            {
                get
                {
                    return ResourceManager.GetString("evSearchingETHStations", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Not Searching Stations.
            /// </summary>
            internal static string evSearchingNone
            {
                get
                {
                    return ResourceManager.GetString("evSearchingNone", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Searching USB Stations.
            /// </summary>
            internal static string evSearchingUSBStations
            {
                get
                {
                    return ResourceManager.GetString("evSearchingUSBStations", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Searching ETH Setting: {0}.
            /// </summary>
            internal static string evSetSearchingETH
            {
                get
                {
                    return ResourceManager.GetString("evSetSearchingETH", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Searching USB Setting: {0}.
            /// </summary>
            internal static string evSetSearchingUSB
            {
                get
                {
                    return ResourceManager.GetString("evSetSearchingUSB", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Service Started.
            /// </summary>
            internal static string evStarted
            {
                get
                {
                    return ResourceManager.GetString("evStarted", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Starting....
            /// </summary>
            internal static string evStarting
            {
                get
                {
                    return ResourceManager.GetString("evStarting", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Service Stopped.
            /// </summary>
            internal static string evStopped
            {
                get
                {
                    return ResourceManager.GetString("evStopped", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Stopping....
            /// </summary>
            internal static string evStopping
            {
                get
                {
                    return ResourceManager.GetString("evStopping", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Stop Searching Ethernet Stations.
            /// </summary>
            internal static string evStopSearchingETHStations
            {
                get
                {
                    return ResourceManager.GetString("evStopSearchingETHStations", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Stop Searching USB Stations.
            /// </summary>
            internal static string evStopSearchingUSBStations
            {
                get
                {
                    return ResourceManager.GetString("evStopSearchingUSBStations", resourceCulture);
                }
            }
        }
    }
}
