// VBConversions Note: VB project level imports
using System.Collections.Generic;
using System;
using System.Linq;
using System.Drawing;
using System.Diagnostics;
using Microsoft.VisualBasic;
using System.Collections;
using System.Windows.Forms;
// End of VB project level imports

using System.Threading;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RemoteManager
{
    namespace My
    {

        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute(),
        global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0"),
        global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
        {

            private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

            #region My.Settings Auto-Save Functionality
#if _MyType
		private static bool addedHandler;
		
		private static object addedHandlerLockObject = new object();
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]private static void AutoSaveSettings(global::System.Object sender, global::System.EventArgs e)
		{
			if ((new Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase()).SaveMySettingsOnExit)
			{
				My.Settings.Default.Save();
			}
		}
#endif
            #endregion

            public static Settings Default
            {
                get
                {

#if _MyType
				if (!addedHandler)
				{
					lock(addedHandlerLockObject)
					{
						if (!addedHandler)
						{
							(new Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase()).Shutdown += AutoSaveSettings;
							addedHandler = true;
						}
					}
				}
#endif
                    return defaultInstance;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute(),
            global::System.Diagnostics.DebuggerNonUserCodeAttribute(),
            global::System.Configuration.DefaultSettingValueAttribute("en")]
            public string optCulture
            {
                get
                {
                    return System.Convert.ToString(this["optCulture"]);
                }
                set
                {
                    this["optCulture"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute(),
            global::System.Diagnostics.DebuggerNonUserCodeAttribute(),
            global::System.Configuration.DefaultSettingValueAttribute("C")]
            public string optTempUnits
            {
                get
                {
                    return System.Convert.ToString(this["optTempUnits"]);
                }
                set
                {
                    this["optTempUnits"] = value;
                }
            }

            [global::System.Configuration.ApplicationScopedSettingAttribute(),
            global::System.Diagnostics.DebuggerNonUserCodeAttribute(),
            global::System.Configuration.DefaultSettingValueAttribute("")]
            public string SupervisorPassword
            {
                get
                {
                    return System.Convert.ToString(this["SupervisorPassword"]);
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute(),
            global::System.Diagnostics.DebuggerNonUserCodeAttribute(),
            global::System.Configuration.DefaultSettingValueAttribute("True")]
            public bool optRegisterMDI
            {
                get
                {
                    return System.Convert.ToBoolean(this["optRegisterMDI"]);
                }
                set
                {
                    this["optRegisterMDI"] = value;
                }
            }

            [global::System.Configuration.ApplicationScopedSettingAttribute(),
            global::System.Diagnostics.DebuggerNonUserCodeAttribute(),
            global::System.Configuration.DefaultSettingValueAttribute("StationGroups.xml")]
            public string xmlStationGroupsFileName
            {
                get
                {
                    return System.Convert.ToString(this["xmlStationGroupsFileName"]);
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute(),
            global::System.Diagnostics.DebuggerNonUserCodeAttribute(),
            global::System.Configuration.DefaultSettingValueAttribute("tempRemoteManager")]
            public string TempUpdateFolder
            {
                get
                {
                    return System.Convert.ToString(this["TempUpdateFolder"]);
                }
                set
                {
                    this["TempUpdateFolder"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute(),
            global::System.Diagnostics.DebuggerNonUserCodeAttribute(),
            global::System.Configuration.DefaultSettingValueAttribute("remoteManagerProgram.jbc")]
            public string AppCompressFileName
            {
                get
                {
                    return System.Convert.ToString(this["AppCompressFileName"]);
                }
                set
                {
                    this["AppCompressFileName"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute(),
            global::System.Diagnostics.DebuggerNonUserCodeAttribute(),
            global::System.Configuration.DefaultSettingValueAttribute("True")]
            public bool optShowErrorNotifications
            {
                get
                {
                    return System.Convert.ToBoolean(this["optShowErrorNotifications"]);
                }
                set
                {
                    this["optShowErrorNotifications"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute(),
            global::System.Diagnostics.DebuggerNonUserCodeAttribute(),
            global::System.Configuration.DefaultSettingValueAttribute("True")]
            public bool optShowStationControllerNotifications
            {
                get
                {
                    return System.Convert.ToBoolean(this["optShowStationControllerNotifications"]);
                }
                set
                {
                    this["optShowStationControllerNotifications"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute(),
            global::System.Diagnostics.DebuggerNonUserCodeAttribute(),
            global::System.Configuration.DefaultSettingValueAttribute("True")]
            public bool optShowStationNotifications
            {
                get
                {
                    return System.Convert.ToBoolean(this["optShowStationNotifications"]);
                }
                set
                {
                    this["optShowStationNotifications"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute(),
            global::System.Diagnostics.DebuggerNonUserCodeAttribute(),
            global::System.Configuration.DefaultSettingValueAttribute("True")]
            public bool WindowStateMaximized
            {
                get
                {
                    return System.Convert.ToBoolean(this["WindowStateMaximized"]);
                }
                set
                {
                    this["WindowStateMaximized"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute(),
            global::System.Diagnostics.DebuggerNonUserCodeAttribute(),
            global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
            public global::System.Drawing.Point WindowLocation
            {
                get
                {
                    return ((global::System.Drawing.Point)(this["WindowLocation"]));
                }
                set
                {
                    this["WindowLocation"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute(),
            global::System.Diagnostics.DebuggerNonUserCodeAttribute(),
            global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
            public global::System.Drawing.Size WindowSize
            {
                get
                {
                    return ((global::System.Drawing.Size)(this["WindowSize"]));
                }
                set
                {
                    this["WindowSize"] = value;
                }
            }
        }
    }

    namespace My
    {

        [global::Microsoft.VisualBasic.HideModuleNameAttribute(),
        global::System.Diagnostics.DebuggerNonUserCodeAttribute(),
        global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        internal sealed class MySettingsProperty
        {

            [global::System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")]
            internal static My.Settings Settings
            {
                get
                {
                    return My.Settings.Default;
                }
            }
        }
    }
}
