//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JBCHostControllerSrv.JBCUpdaterService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="faultError", Namespace="http://schemas.datacontract.org/2004/07/JBCUpdaterSrv")]
    [System.SerializableAttribute()]
    public partial class faultError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JBCHostControllerSrv.JBCUpdaterService.dc_EnumConstJBCdc_FaultError CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JBCHostControllerSrv.JBCUpdaterService.dc_EnumConstJBCdc_FaultError Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operation {
            get {
                return this.OperationField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationField, value) != true)) {
                    this.OperationField = value;
                    this.RaisePropertyChanged("Operation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dc_EnumConstJBC.dc_FaultError", Namespace="http://schemas.datacontract.org/2004/07/JBCUpdaterSrv")]
    public enum dc_EnumConstJBCdc_FaultError : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoError = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotControlledError = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StationNotFound = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StationError = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ToolError = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotValidTool = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FunctionNotSupported = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dc_EnumConstJBC.dc_UpdateState", Namespace="http://schemas.datacontract.org/2004/07/JBCUpdaterSrv")]
    public enum dc_EnumConstJBCdc_UpdateState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Finished = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Updating = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://JBCUpdaterSrv", ConfigurationName="JBCUpdaterService.IJBCUpdaterService")]
    public interface IJBCUpdaterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://JBCUpdaterSrv/IJBCUpdaterService/ReceiveFile", ReplyAction="http://JBCUpdaterSrv/IJBCUpdaterService/ReceiveFileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(JBCHostControllerSrv.JBCUpdaterService.faultError), Action="http://JBCUpdaterSrv/IJBCUpdaterService/ReceiveFilefaultErrorFault", Name="faultError", Namespace="http://schemas.datacontract.org/2004/07/JBCUpdaterSrv")]
        int ReceiveFile(int nSequence, byte[] bytes);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://JBCUpdaterSrv/IJBCUpdaterService/InitUpdate")]
        void InitUpdate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://JBCUpdaterSrv/IJBCUpdaterService/StateUpdate", ReplyAction="http://JBCUpdaterSrv/IJBCUpdaterService/StateUpdateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(JBCHostControllerSrv.JBCUpdaterService.faultError), Action="http://JBCUpdaterSrv/IJBCUpdaterService/StateUpdatefaultErrorFault", Name="faultError", Namespace="http://schemas.datacontract.org/2004/07/JBCUpdaterSrv")]
        JBCHostControllerSrv.JBCUpdaterService.dc_EnumConstJBCdc_UpdateState StateUpdate();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJBCUpdaterServiceChannel : JBCHostControllerSrv.JBCUpdaterService.IJBCUpdaterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JBCUpdaterServiceClient : System.ServiceModel.ClientBase<JBCHostControllerSrv.JBCUpdaterService.IJBCUpdaterService>, JBCHostControllerSrv.JBCUpdaterService.IJBCUpdaterService {
        
        public JBCUpdaterServiceClient() {
        }
        
        public JBCUpdaterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JBCUpdaterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JBCUpdaterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JBCUpdaterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ReceiveFile(int nSequence, byte[] bytes) {
            return base.Channel.ReceiveFile(nSequence, bytes);
        }
        
        public void InitUpdate() {
            base.Channel.InitUpdate();
        }
        
        public JBCHostControllerSrv.JBCUpdaterService.dc_EnumConstJBCdc_UpdateState StateUpdate() {
            return base.Channel.StateUpdate();
        }
    }
}
