//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace RemoteManRegister
{
    namespace My.Resources
    {
        using System;


        /// <summary>
        ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
        /// </summary>
        // StronglyTypedResourceBuilder generó automáticamente esta clase
        // a través de una herramienta como ResGen o Visual Studio.
        // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
        // con la opción /str o recompile su proyecto de VS.
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]

        public class Resources
        {

            private static global::System.Resources.ResourceManager resourceMan;

            private static global::System.Globalization.CultureInfo resourceCulture;

            [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
            internal Resources()
            {
            }

            /// <summary>
            ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
            /// </summary>
            [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
            public static global::System.Resources.ResourceManager ResourceManager
            {
                get
                {
                    if (object.ReferenceEquals(resourceMan, null))
                    {
                        global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RemoteManRegister.Properties.Resources", typeof(Resources).Assembly);
                        resourceMan = temp;
                    }
                    return resourceMan;
                }
            }

            /// <summary>
            ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
            ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
            /// </summary>
            [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
            public static global::System.Globalization.CultureInfo Culture
            {
                get
                {
                    return resourceCulture;
                }
                set
                {
                    resourceCulture = value;
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Comma-separated values  (*.csv)|*.csv.
            /// </summary>
            public static string filterCommaSeparated
            {
                get
                {
                    return ResourceManager.GetString("filterCommaSeparated", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a LabRegister file (*.lbr)|*.lbr.
            /// </summary>
            public static string filterLabRegister
            {
                get
                {
                    return ResourceManager.GetString("filterLabRegister", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Done.
            /// </summary>
            public static string gralDone
            {
                get
                {
                    return ResourceManager.GetString("gralDone", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Flow.
            /// </summary>
            public static string gralFlow
            {
                get
                {
                    return ResourceManager.GetString("gralFlow", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Power.
            /// </summary>
            public static string gralPower
            {
                get
                {
                    return ResourceManager.GetString("gralPower", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Temperature.
            /// </summary>
            public static string gralTemperature
            {
                get
                {
                    return ResourceManager.GetString("gralTemperature", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Warning!.
            /// </summary>
            public static string gralWarning
            {
                get
                {
                    return ResourceManager.GetString("gralWarning", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Add.
            /// </summary>
            public static string regAdd
            {
                get
                {
                    return ResourceManager.GetString("regAdd", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Axis.
            /// </summary>
            public static string regAxisGridAxis
            {
                get
                {
                    return ResourceManager.GetString("regAxisGridAxis", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Grid.
            /// </summary>
            public static string regAxisGridGrid
            {
                get
                {
                    return ResourceManager.GetString("regAxisGridGrid", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Grid Step.
            /// </summary>
            public static string regAxisGridGridStep
            {
                get
                {
                    return ResourceManager.GetString("regAxisGridGridStep", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a (seconds).
            /// </summary>
            public static string regAxisGridSeconds
            {
                get
                {
                    return ResourceManager.GetString("regAxisGridSeconds", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Time Window.
            /// </summary>
            public static string regAxisGridTimeWindow
            {
                get
                {
                    return ResourceManager.GetString("regAxisGridTimeWindow", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Cancel.
            /// </summary>
            public static string regButCancel
            {
                get
                {
                    return ResourceManager.GetString("regButCancel", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Ok.
            /// </summary>
            public static string regButOk
            {
                get
                {
                    return ResourceManager.GetString("regButOk", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a File {0} cannot be created (error: {1}).
            /// </summary>
            public static string regCannotCreateFile
            {
                get
                {
                    return ResourceManager.GetString("regCannotCreateFile", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a File {0} cannot be opened (error: {1}).
            /// </summary>
            public static string regCannotOpenFile
            {
                get
                {
                    return ResourceManager.GetString("regCannotOpenFile", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Time:.
            /// </summary>
            public static string regCoordTime
            {
                get
                {
                    return ResourceManager.GetString("regCoordTime", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Data series will be lost. Are you sure to continue?.
            /// </summary>
            public static string regDataLost
            {
                get
                {
                    return ResourceManager.GetString("regDataLost", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Enter the desired title for the plot..
            /// </summary>
            public static string regEnterPlotTitle
            {
                get
                {
                    return ResourceManager.GetString("regEnterPlotTitle", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Finish.
            /// </summary>
            public static string regFinish
            {
                get
                {
                    return ResourceManager.GetString("regFinish", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Configuration.
            /// </summary>
            public static string regMnuConfig
            {
                get
                {
                    return ResourceManager.GetString("regMnuConfig", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Axis and Grid.
            /// </summary>
            public static string regMnuConfigAxis
            {
                get
                {
                    return ResourceManager.GetString("regMnuConfigAxis", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Options.
            /// </summary>
            public static string regMnuConfigOptions
            {
                get
                {
                    return ResourceManager.GetString("regMnuConfigOptions", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Series.
            /// </summary>
            public static string regMnuConfigSeries
            {
                get
                {
                    return ResourceManager.GetString("regMnuConfigSeries", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Templates.
            /// </summary>
            public static string regMnuConfigTemplates
            {
                get
                {
                    return ResourceManager.GetString("regMnuConfigTemplates", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Load.
            /// </summary>
            public static string regMnuConfigTemplatesLoad
            {
                get
                {
                    return ResourceManager.GetString("regMnuConfigTemplatesLoad", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Save.
            /// </summary>
            public static string regMnuConfigTemplatesSave
            {
                get
                {
                    return ResourceManager.GetString("regMnuConfigTemplatesSave", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Title.
            /// </summary>
            public static string regMnuConfigTitle
            {
                get
                {
                    return ResourceManager.GetString("regMnuConfigTitle", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Wizard.
            /// </summary>
            public static string regMnuConfigWizard
            {
                get
                {
                    return ResourceManager.GetString("regMnuConfigWizard", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a File.
            /// </summary>
            public static string regMnuFile
            {
                get
                {
                    return ResourceManager.GetString("regMnuFile", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Export to CSV.
            /// </summary>
            public static string regMnuFileExportToCSV
            {
                get
                {
                    return ResourceManager.GetString("regMnuFileExportToCSV", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a New.
            /// </summary>
            public static string regMnuFileNew
            {
                get
                {
                    return ResourceManager.GetString("regMnuFileNew", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Open.
            /// </summary>
            public static string regMnuFileOpen
            {
                get
                {
                    return ResourceManager.GetString("regMnuFileOpen", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Print.
            /// </summary>
            public static string regMnuFilePrint
            {
                get
                {
                    return ResourceManager.GetString("regMnuFilePrint", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Save As.
            /// </summary>
            public static string regMnuFileSaveAs
            {
                get
                {
                    return ResourceManager.GetString("regMnuFileSaveAs", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Modify.
            /// </summary>
            public static string regModify
            {
                get
                {
                    return ResourceManager.GetString("regModify", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a File extension must be .lbr or .csv.
            /// </summary>
            public static string regMsgExtNotValid
            {
                get
                {
                    return ResourceManager.GetString("regMsgExtNotValid", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Generating [0].
            /// </summary>
            public static string regMsgGeneratingExt
            {
                get
                {
                    return ResourceManager.GetString("regMsgGeneratingExt", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Generating [0]. Please wait....
            /// </summary>
            public static string regMsgGeneratingFile
            {
                get
                {
                    return ResourceManager.GetString("regMsgGeneratingFile", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Loading [0].
            /// </summary>
            public static string regMsgLoadingExt
            {
                get
                {
                    return ResourceManager.GetString("regMsgLoadingExt", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Loading [0]. Please wait....
            /// </summary>
            public static string regMsgLoadingFile
            {
                get
                {
                    return ResourceManager.GetString("regMsgLoadingFile", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Next.
            /// </summary>
            public static string regNext
            {
                get
                {
                    return ResourceManager.GetString("regNext", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a It is not a LBR file or is corrupted..
            /// </summary>
            public static string regNotLBRFile
            {
                get
                {
                    return ResourceManager.GetString("regNotLBRFile", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Background.
            /// </summary>
            public static string regOptClrBackground
            {
                get
                {
                    return ResourceManager.GetString("regOptClrBackground", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Restore Defaults.
            /// </summary>
            public static string regOptClrDefaults
            {
                get
                {
                    return ResourceManager.GetString("regOptClrDefaults", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Grid Divisions.
            /// </summary>
            public static string regOptClrGridDiv
            {
                get
                {
                    return ResourceManager.GetString("regOptClrGridDiv", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Power Axis.
            /// </summary>
            public static string regOptClrPowerAxis
            {
                get
                {
                    return ResourceManager.GetString("regOptClrPowerAxis", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Series Text.
            /// </summary>
            public static string regOptClrSeriesText
            {
                get
                {
                    return ResourceManager.GetString("regOptClrSeriesText", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Temperature Axis.
            /// </summary>
            public static string regOptClrTempAxis
            {
                get
                {
                    return ResourceManager.GetString("regOptClrTempAxis", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Time Axis.
            /// </summary>
            public static string regOptClrTimeAxis
            {
                get
                {
                    return ResourceManager.GetString("regOptClrTimeAxis", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Title Text.
            /// </summary>
            public static string regOptClrTitle
            {
                get
                {
                    return ResourceManager.GetString("regOptClrTitle", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Colors.
            /// </summary>
            public static string regOptColors
            {
                get
                {
                    return ResourceManager.GetString("regOptColors", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Lines and Points.
            /// </summary>
            public static string regOptLinesAndPoints
            {
                get
                {
                    return ResourceManager.GetString("regOptLinesAndPoints", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Line Width (pix.).
            /// </summary>
            public static string regOptLineWidth
            {
                get
                {
                    return ResourceManager.GetString("regOptLineWidth", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Point Width (pix.).
            /// </summary>
            public static string regOptPointWidth
            {
                get
                {
                    return ResourceManager.GetString("regOptPointWidth", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Plot Starting Side.
            /// </summary>
            public static string regOptStartSide
            {
                get
                {
                    return ResourceManager.GetString("regOptStartSide", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a From left.
            /// </summary>
            public static string regOptStartSideLeft
            {
                get
                {
                    return ResourceManager.GetString("regOptStartSideLeft", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a From right.
            /// </summary>
            public static string regOptStartSideRight
            {
                get
                {
                    return ResourceManager.GetString("regOptStartSideRight", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a It starts when extract the tool out of the stand.
            /// </summary>
            public static string regOptTriggerAutoInfo
            {
                get
                {
                    return ResourceManager.GetString("regOptTriggerAutoInfo", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a It starts and finishes by using the buttons in the plot.
            /// </summary>
            public static string regOptTriggerManualInfo
            {
                get
                {
                    return ResourceManager.GetString("regOptTriggerManualInfo", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a It starts when extract the tool out of the stand and finishes when time window is reached.
            /// </summary>
            public static string regOptTriggerSingleInfo
            {
                get
                {
                    return ResourceManager.GetString("regOptTriggerSingleInfo", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a There is a station defined for this plot, already plotting in another window..
            /// </summary>
            public static string regPlottingInAnotherWindow
            {
                get
                {
                    return ResourceManager.GetString("regPlottingInAnotherWindow", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Plot Title.
            /// </summary>
            public static string regPlotTitle
            {
                get
                {
                    return ResourceManager.GetString("regPlotTitle", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Previous.
            /// </summary>
            public static string regPrevious
            {
                get
                {
                    return ResourceManager.GetString("regPrevious", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Remove.
            /// </summary>
            public static string regRemove
            {
                get
                {
                    return ResourceManager.GetString("regRemove", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a {0} Sec/Tick.
            /// </summary>
            public static string regSecondsPerTick
            {
                get
                {
                    return ResourceManager.GetString("regSecondsPerTick", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a This magnitude is not compatible with the selected station..
            /// </summary>
            public static string regSeriesCannotSelectMagnitude
            {
                get
                {
                    return ResourceManager.GetString("regSeriesCannotSelectMagnitude", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a List of Series.
            /// </summary>
            public static string regSeriesListOfSeries
            {
                get
                {
                    return ResourceManager.GetString("regSeriesListOfSeries", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Flow ( % ).
            /// </summary>
            public static string regSeriesMagnitudeFlow
            {
                get
                {
                    return ResourceManager.GetString("regSeriesMagnitudeFlow", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Power ( % ).
            /// </summary>
            public static string regSeriesMagnitudePower
            {
                get
                {
                    return ResourceManager.GetString("regSeriesMagnitudePower", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Temperature ( {0} ).
            /// </summary>
            public static string regSeriesMagnitudeTemp
            {
                get
                {
                    return ResourceManager.GetString("regSeriesMagnitudeTemp", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Color.
            /// </summary>
            public static string regSeriesSerieColor
            {
                get
                {
                    return ResourceManager.GetString("regSeriesSerieColor", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Select....
            /// </summary>
            public static string regSeriesSerieColorSelect
            {
                get
                {
                    return ResourceManager.GetString("regSeriesSerieColorSelect", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Serie Data.
            /// </summary>
            public static string regSeriesSerieData
            {
                get
                {
                    return ResourceManager.GetString("regSeriesSerieData", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Line.
            /// </summary>
            public static string regSeriesSerieLine
            {
                get
                {
                    return ResourceManager.GetString("regSeriesSerieLine", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Magnitude.
            /// </summary>
            public static string regSeriesSerieMagnitude
            {
                get
                {
                    return ResourceManager.GetString("regSeriesSerieMagnitude", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Name.
            /// </summary>
            public static string regSeriesSerieName
            {
                get
                {
                    return ResourceManager.GetString("regSeriesSerieName", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Points.
            /// </summary>
            public static string regSeriesSeriePoints
            {
                get
                {
                    return ResourceManager.GetString("regSeriesSeriePoints", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Port.
            /// </summary>
            public static string regSeriesSeriePort
            {
                get
                {
                    return ResourceManager.GetString("regSeriesSeriePort", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Show Line.
            /// </summary>
            public static string regSeriesSerieShowLine
            {
                get
                {
                    return ResourceManager.GetString("regSeriesSerieShowLine", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Show Points.
            /// </summary>
            public static string regSeriesSerieShowPoints
            {
                get
                {
                    return ResourceManager.GetString("regSeriesSerieShowPoints", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Station.
            /// </summary>
            public static string regSeriesSerieStation
            {
                get
                {
                    return ResourceManager.GetString("regSeriesSerieStation", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a No Name.
            /// </summary>
            public static string regSeriesSerieStationNoName
            {
                get
                {
                    return ResourceManager.GetString("regSeriesSerieStationNoName", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Coordinates.
            /// </summary>
            public static string regStripCoordinates
            {
                get
                {
                    return ResourceManager.GetString("regStripCoordinates", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Default Zoom.
            /// </summary>
            public static string regStripDefaultZoom
            {
                get
                {
                    return ResourceManager.GetString("regStripDefaultZoom", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Pause.
            /// </summary>
            public static string regStripPause
            {
                get
                {
                    return ResourceManager.GetString("regStripPause", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Play.
            /// </summary>
            public static string regStripPlay
            {
                get
                {
                    return ResourceManager.GetString("regStripPlay", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Record.
            /// </summary>
            public static string regStripRecord
            {
                get
                {
                    return ResourceManager.GetString("regStripRecord", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Reset Trigger Detection.
            /// </summary>
            public static string regStripResetTrigger
            {
                get
                {
                    return ResourceManager.GetString("regStripResetTrigger", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Paused.
            /// </summary>
            public static string regStripStatusPause
            {
                get
                {
                    return ResourceManager.GetString("regStripStatusPause", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Playing.
            /// </summary>
            public static string regStripStatusPlay
            {
                get
                {
                    return ResourceManager.GetString("regStripStatusPlay", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Recording.
            /// </summary>
            public static string regStripStatusRecord
            {
                get
                {
                    return ResourceManager.GetString("regStripStatusRecord", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Stopped.
            /// </summary>
            public static string regStripStatusStop
            {
                get
                {
                    return ResourceManager.GetString("regStripStatusStop", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Stop.
            /// </summary>
            public static string regStripStop
            {
                get
                {
                    return ResourceManager.GetString("regStripStop", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Trigger.
            /// </summary>
            public static string regStripTrigger
            {
                get
                {
                    return ResourceManager.GetString("regStripTrigger", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Auto.
            /// </summary>
            public static string regStripTriggerAuto
            {
                get
                {
                    return ResourceManager.GetString("regStripTriggerAuto", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Manual.
            /// </summary>
            public static string regStripTriggerManual
            {
                get
                {
                    return ResourceManager.GetString("regStripTriggerManual", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Single.
            /// </summary>
            public static string regStripTriggerSingle
            {
                get
                {
                    return ResourceManager.GetString("regStripTriggerSingle", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Zoom.
            /// </summary>
            public static string regStripZoom
            {
                get
                {
                    return ResourceManager.GetString("regStripZoom", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Template.
            /// </summary>
            public static string regTemplate
            {
                get
                {
                    return ResourceManager.GetString("regTemplate", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a myTemplateName.
            /// </summary>
            public static string regTemplateDefaultName
            {
                get
                {
                    return ResourceManager.GetString("regTemplateDefaultName", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Please, type the name for the template..
            /// </summary>
            public static string regTemplateEnterName
            {
                get
                {
                    return ResourceManager.GetString("regTemplateEnterName", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Template List.
            /// </summary>
            public static string regTemplateList
            {
                get
                {
                    return ResourceManager.GetString("regTemplateList", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Template Parameters.
            /// </summary>
            public static string regTemplateParams
            {
                get
                {
                    return ResourceManager.GetString("regTemplateParams", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Series.
            /// </summary>
            public static string regTemplateSeriesData
            {
                get
                {
                    return ResourceManager.GetString("regTemplateSeriesData", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Trigger.
            /// </summary>
            public static string regTemplateTrigger
            {
                get
                {
                    return ResourceManager.GetString("regTemplateTrigger", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Time.
            /// </summary>
            public static string regTime
            {
                get
                {
                    return ResourceManager.GetString("regTime", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Step 1 of 2. Please, connect the stations from where data is desired. Then add the desired series to be shown in the plot by setting the parameters and click on the &apos;Add&apos; button. Finally, type the desired title for your plot..
            /// </summary>
            public static string regWiz1Info
            {
                get
                {
                    return ResourceManager.GetString("regWiz1Info", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Step 2 of 2. Select the axis ranges and the grid steps. For the time axis the value represent a time window..
            /// </summary>
            public static string regWiz2Info
            {
                get
                {
                    return ResourceManager.GetString("regWiz2Info", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Axis Range.
            /// </summary>
            public static string regWizard2AxisRange
            {
                get
                {
                    return ResourceManager.GetString("regWizard2AxisRange", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Series and Title.
            /// </summary>
            public static string regWizardSeriesAndTitle
            {
                get
                {
                    return ResourceManager.GetString("regWizardSeriesAndTitle", resourceCulture);
                }
            }
        }
    }
}
