//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace RemoteManRegister
{
    namespace My
    {


        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
        internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
        {

            private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

            public static Settings Default
            {
                get
                {
                    return defaultInstance;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("150, 150")]
            public global::System.Drawing.Point AppPosition
            {
                get
                {
                    return ((global::System.Drawing.Point)(this["AppPosition"]));
                }
                set
                {
                    this["AppPosition"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("800, 600")]
            public global::System.Drawing.Size AppSize
            {
                get
                {
                    return ((global::System.Drawing.Size)(this["AppSize"]));
                }
                set
                {
                    this["AppSize"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>25 ºC - 400 ºC</string>
  <string>200 ºC - 400 ºC</string>
  <string>300 ºC - 400 ºC</string>
</ArrayOfString>")]
            public global::System.Collections.Specialized.StringCollection AxisTempRange
            {
                get
                {
                    return ((global::System.Collections.Specialized.StringCollection)(this["AxisTempRange"]));
                }
                set
                {
                    this["AxisTempRange"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0 % - 10 %</string>
  <string>0 % - 20 %</string>
  <string>0 % - 50 %</string>
  <string>0 % - 100 %</string>
</ArrayOfString>")]
            public global::System.Collections.Specialized.StringCollection AxisPwrRange
            {
                get
                {
                    return ((global::System.Collections.Specialized.StringCollection)(this["AxisPwrRange"]));
                }
                set
                {
                    this["AxisPwrRange"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>25</string>
  <string>50</string>
  <string>75</string>
  <string>100</string>
</ArrayOfString>")]
            public global::System.Collections.Specialized.StringCollection GridTempSteps
            {
                get
                {
                    return ((global::System.Collections.Specialized.StringCollection)(this["GridTempSteps"]));
                }
                set
                {
                    this["GridTempSteps"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>5</string>
  <string>10</string>
  <string>25</string>
  <string>50</string>
</ArrayOfString>")]
            public global::System.Collections.Specialized.StringCollection GridPwrSteps
            {
                get
                {
                    return ((global::System.Collections.Specialized.StringCollection)(this["GridPwrSteps"]));
                }
                set
                {
                    this["GridPwrSteps"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>25</string>
  <string>50</string>
  <string>75</string>
  <string>100</string>
  <string>125</string>
  <string>150</string>
  <string>175</string>
  <string>200</string>
  <string>225</string>
  <string>250</string>
  <string>275</string>
  <string>300</string>
  <string>325</string>
  <string>350</string>
  <string>375</string>
  <string>400</string>
  <string>425</string>
  <string>450</string>
  <string>475</string>
  <string>500</string>
</ArrayOfString>")]
            public global::System.Collections.Specialized.StringCollection AxisTempCustom
            {
                get
                {
                    return ((global::System.Collections.Specialized.StringCollection)(this["AxisTempCustom"]));
                }
                set
                {
                    this["AxisTempCustom"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("0")]
            public double Pmin
            {
                get
                {
                    return ((double)(this["Pmin"]));
                }
                set
                {
                    this["Pmin"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("100")]
            public double Pmax
            {
                get
                {
                    return ((double)(this["Pmax"]));
                }
                set
                {
                    this["Pmax"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("25")]
            public double Tmin
            {
                get
                {
                    return ((double)(this["Tmin"]));
                }
                set
                {
                    this["Tmin"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("400")]
            public double Tmax
            {
                get
                {
                    return ((double)(this["Tmax"]));
                }
                set
                {
                    this["Tmax"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("10")]
            public double Pstep
            {
                get
                {
                    return ((double)(this["Pstep"]));
                }
                set
                {
                    this["Pstep"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("25")]
            public double Tstep
            {
                get
                {
                    return ((double)(this["Tstep"]));
                }
                set
                {
                    this["Tstep"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("0")]
            public int rulerAxis
            {
                get
                {
                    return ((int)(this["rulerAxis"]));
                }
                set
                {
                    this["rulerAxis"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("30")]
            public double timeRange
            {
                get
                {
                    return ((double)(this["timeRange"]));
                }
                set
                {
                    this["timeRange"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("1")]
            public double timeStep
            {
                get
                {
                    return ((double)(this["timeStep"]));
                }
                set
                {
                    this["timeStep"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0</string>
  <string>5</string>
  <string>10</string>
  <string>15</string>
  <string>20</string>
  <string>25</string>
  <string>30</string>
  <string>35</string>
  <string>40</string>
  <string>45</string>
  <string>50</string>
  <string>55</string>
  <string>60</string>
  <string>65</string>
  <string>70</string>
  <string>75</string>
  <string>80</string>
  <string>85</string>
  <string>90</string>
  <string>95</string>
  <string>100</string>
</ArrayOfString>")]
            public global::System.Collections.Specialized.StringCollection AxisPwrCustom
            {
                get
                {
                    return ((global::System.Collections.Specialized.StringCollection)(this["AxisPwrCustom"]));
                }
                set
                {
                    this["AxisPwrCustom"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>10</string>
  <string>30</string>
  <string>60</string>
  <string>120</string>
  <string>300</string>
</ArrayOfString>")]
            public global::System.Collections.Specialized.StringCollection AxisTimeRange
            {
                get
                {
                    return ((global::System.Collections.Specialized.StringCollection)(this["AxisTimeRange"]));
                }
                set
                {
                    this["AxisTimeRange"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>1</string>
  <string>2</string>
  <string>5</string>
  <string>10</string>
  <string>20</string>
  <string>30</string>
  <string>60</string>
  <string>120</string>
</ArrayOfString>")]
            public global::System.Collections.Specialized.StringCollection GridTimeStep
            {
                get
                {
                    return ((global::System.Collections.Specialized.StringCollection)(this["GridTimeStep"]));
                }
                set
                {
                    this["GridTimeStep"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>red</string>
  <string>blue</string>
  <string>green</string>
  <string>orange</string>
  <string>yellow</string>
  <string>cyan</string>
  <string>brown</string>
  <string>violet</string>
</ArrayOfString>")]
            public global::System.Collections.Specialized.StringCollection serieColors
            {
                get
                {
                    return ((global::System.Collections.Specialized.StringCollection)(this["serieColors"]));
                }
                set
                {
                    this["serieColors"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool AppMaximized
            {
                get
                {
                    return ((bool)(this["AppMaximized"]));
                }
                set
                {
                    this["AppMaximized"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("30")]
            public double timeMax
            {
                get
                {
                    return ((double)(this["timeMax"]));
                }
                set
                {
                    this["timeMax"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("0")]
            public double timeMin
            {
                get
                {
                    return ((double)(this["timeMin"]));
                }
                set
                {
                    this["timeMin"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("Black")]
            public global::System.Drawing.Color axisTempClr
            {
                get
                {
                    return ((global::System.Drawing.Color)(this["axisTempClr"]));
                }
                set
                {
                    this["axisTempClr"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("Black")]
            public global::System.Drawing.Color axisPwrClr
            {
                get
                {
                    return ((global::System.Drawing.Color)(this["axisPwrClr"]));
                }
                set
                {
                    this["axisPwrClr"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("Black")]
            public global::System.Drawing.Color axisTimeClr
            {
                get
                {
                    return ((global::System.Drawing.Color)(this["axisTimeClr"]));
                }
                set
                {
                    this["axisTimeClr"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("200, 200, 200")]
            public global::System.Drawing.Color gridClr
            {
                get
                {
                    return ((global::System.Drawing.Color)(this["gridClr"]));
                }
                set
                {
                    this["gridClr"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("Black")]
            public global::System.Drawing.Color textClr
            {
                get
                {
                    return ((global::System.Drawing.Color)(this["textClr"]));
                }
                set
                {
                    this["textClr"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("WhiteSmoke")]
            public global::System.Drawing.Color bckGnd
            {
                get
                {
                    return ((global::System.Drawing.Color)(this["bckGnd"]));
                }
                set
                {
                    this["bckGnd"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("Black")]
            public global::System.Drawing.Color titleClr
            {
                get
                {
                    return ((global::System.Drawing.Color)(this["titleClr"]));
                }
                set
                {
                    this["titleClr"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("3")]
            public int lineWidth
            {
                get
                {
                    return ((int)(this["lineWidth"]));
                }
                set
                {
                    this["lineWidth"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("6")]
            public int pointWidth
            {
                get
                {
                    return ((int)(this["pointWidth"]));
                }
                set
                {
                    this["pointWidth"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>50 ºF - 750 ºF</string>
  <string>400 ºF - 750 ºF</string>
  <string>550 ºF - 750 ºF</string>
</ArrayOfString>")]
            public global::System.Collections.Specialized.StringCollection AxisTempRangeF
            {
                get
                {
                    return ((global::System.Collections.Specialized.StringCollection)(this["AxisTempRangeF"]));
                }
                set
                {
                    this["AxisTempRangeF"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>25</string>
  <string>50</string>
  <string>75</string>
  <string>100</string>
</ArrayOfString>")]
            public global::System.Collections.Specialized.StringCollection GridTempStepsF
            {
                get
                {
                    return ((global::System.Collections.Specialized.StringCollection)(this["GridTempStepsF"]));
                }
                set
                {
                    this["GridTempStepsF"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>50</string>
  <string>100</string>
  <string>150</string>
  <string>200</string>
  <string>250</string>
  <string>300</string>
  <string>350</string>
  <string>400</string>
  <string>450</string>
  <string>500</string>
  <string>550</string>
  <string>600</string>
  <string>650</string>
  <string>700</string>
  <string>750</string>
  <string>800</string>
  <string>850</string>
  <string>900</string>
  <string>950</string>
</ArrayOfString>")]
            public global::System.Collections.Specialized.StringCollection AxisTempCustomF
            {
                get
                {
                    return ((global::System.Collections.Specialized.StringCollection)(this["AxisTempCustomF"]));
                }
                set
                {
                    this["AxisTempCustomF"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("75")]
            public double TminF
            {
                get
                {
                    return ((double)(this["TminF"]));
                }
                set
                {
                    this["TminF"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("750")]
            public double TmaxF
            {
                get
                {
                    return ((double)(this["TmaxF"]));
                }
                set
                {
                    this["TmaxF"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("45")]
            public double TstepF
            {
                get
                {
                    return ((double)(this["TstepF"]));
                }
                set
                {
                    this["TstepF"] = value;
                }
            }
        }
    }
}
