'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.36366
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("JBCTraceControlLocalSrv.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Function not supported.
        '''</summary>
        Friend ReadOnly Property errFunctionNotSupported() As String
            Get
                Return ResourceManager.GetString("errFunctionNotSupported", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not controlled error. See Detail data..
        '''</summary>
        Friend ReadOnly Property errNotControlled() As String
            Get
                Return ResourceManager.GetString("errNotControlled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not valid tool..
        '''</summary>
        Friend ReadOnly Property errNotValidTool() As String
            Get
                Return ResourceManager.GetString("errNotValidTool", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error in service. See Detail data..
        '''</summary>
        Friend ReadOnly Property errServiceError() As String
            Get
                Return ResourceManager.GetString("errServiceError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Station not found..
        '''</summary>
        Friend ReadOnly Property errStationNotFound() As String
            Get
                Return ResourceManager.GetString("errStationNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error creating service.
        '''</summary>
        Friend ReadOnly Property evErrorCreating() As String
            Get
                Return ResourceManager.GetString("evErrorCreating", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Custom Command Error.
        '''</summary>
        Friend ReadOnly Property evErrorOnCustomCommand() As String
            Get
                Return ResourceManager.GetString("evErrorOnCustomCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error starting JBC Connect DLL.
        '''</summary>
        Friend ReadOnly Property evErrorStartingDLL() As String
            Get
                Return ResourceManager.GetString("evErrorStartingDLL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Event Service.
        '''</summary>
        Friend ReadOnly Property evNew() As String
            Get
                Return ResourceManager.GetString("evNew", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Off.
        '''</summary>
        Friend ReadOnly Property evOff() As String
            Get
                Return ResourceManager.GetString("evOff", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to On.
        '''</summary>
        Friend ReadOnly Property evOn() As String
            Get
                Return ResourceManager.GetString("evOn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Searching Ethernet Stations.
        '''</summary>
        Friend ReadOnly Property evSearchingETHStations() As String
            Get
                Return ResourceManager.GetString("evSearchingETHStations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not Searching Stations.
        '''</summary>
        Friend ReadOnly Property evSearchingNone() As String
            Get
                Return ResourceManager.GetString("evSearchingNone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Searching USB Stations.
        '''</summary>
        Friend ReadOnly Property evSearchingUSBStations() As String
            Get
                Return ResourceManager.GetString("evSearchingUSBStations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Searching ETH Setting: {0}.
        '''</summary>
        Friend ReadOnly Property evSetSearchingETH() As String
            Get
                Return ResourceManager.GetString("evSetSearchingETH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Searching USB Setting: {0}.
        '''</summary>
        Friend ReadOnly Property evSetSearchingUSB() As String
            Get
                Return ResourceManager.GetString("evSetSearchingUSB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Service Started.
        '''</summary>
        Friend ReadOnly Property evStarted() As String
            Get
                Return ResourceManager.GetString("evStarted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Starting....
        '''</summary>
        Friend ReadOnly Property evStarting() As String
            Get
                Return ResourceManager.GetString("evStarting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Service Stopped.
        '''</summary>
        Friend ReadOnly Property evStopped() As String
            Get
                Return ResourceManager.GetString("evStopped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stopping....
        '''</summary>
        Friend ReadOnly Property evStopping() As String
            Get
                Return ResourceManager.GetString("evStopping", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stop Searching Ethernet Stations.
        '''</summary>
        Friend ReadOnly Property evStopSearchingETHStations() As String
            Get
                Return ResourceManager.GetString("evStopSearchingETHStations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stop Searching USB Stations.
        '''</summary>
        Friend ReadOnly Property evStopSearchingUSBStations() As String
            Get
                Return ResourceManager.GetString("evStopSearchingUSBStations", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
