//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace JBCResetCounters
{
    namespace My.Resources
    {
        using System;


        /// <summary>
        ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
        /// </summary>
        // StronglyTypedResourceBuilder generó automáticamente esta clase
        // a través de una herramienta como ResGen o Visual Studio.
        // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
        // con la opción /str o recompile su proyecto de VS.
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]

        public class Resources
        {

            private static global::System.Resources.ResourceManager resourceMan;

            private static global::System.Globalization.CultureInfo resourceCulture;

            [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
            internal Resources()
            {
            }

            /// <summary>
            ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
            /// </summary>
            [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
            public static global::System.Resources.ResourceManager ResourceManager
            {
                get
                {
                    if (object.ReferenceEquals(resourceMan, null))
                    {
                        global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("My.Resources.Resources", typeof(Resources).Assembly);
                        resourceMan = temp;
                    }
                    return resourceMan;
                }
            }

            /// <summary>
            ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
            ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
            /// </summary>
            [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
            public static global::System.Globalization.CultureInfo Culture
            {
                get
                {
                    return resourceCulture;
                }
                set
                {
                    resourceCulture = value;
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a JBC Reset Counters.
            /// </summary>
            public static string tApplicTitle
            {
                get
                {
                    return ResourceManager.GetString("tApplicTitle", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Reset All Counters.
            /// </summary>
            public static string tcolButResetAllCounters
            {
                get
                {
                    return ResourceManager.GetString("tcolButResetAllCounters", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Reset Partial Counters.
            /// </summary>
            public static string tcolButResetPartialCounters
            {
                get
                {
                    return ResourceManager.GetString("tcolButResetPartialCounters", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Connection.
            /// </summary>
            public static string tcolCOM
            {
                get
                {
                    return ResourceManager.GetString("tcolCOM", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a HW.
            /// </summary>
            public static string tcolHW
            {
                get
                {
                    return ResourceManager.GetString("tcolHW", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Model.
            /// </summary>
            public static string tcolModel
            {
                get
                {
                    return ResourceManager.GetString("tcolModel", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Model Type.
            /// </summary>
            public static string tcolModelType
            {
                get
                {
                    return ResourceManager.GetString("tcolModelType", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Model Version.
            /// </summary>
            public static string tcolModelVersion
            {
                get
                {
                    return ResourceManager.GetString("tcolModelVersion", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Name.
            /// </summary>
            public static string tcolName
            {
                get
                {
                    return ResourceManager.GetString("tcolName", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Protocol.
            /// </summary>
            public static string tcolProtocol
            {
                get
                {
                    return ResourceManager.GetString("tcolProtocol", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a SW.
            /// </summary>
            public static string tcolSW
            {
                get
                {
                    return ResourceManager.GetString("tcolSW", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Are you sure?.
            /// </summary>
            public static string tConfirmAction
            {
                get
                {
                    return ResourceManager.GetString("tConfirmAction", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Counter.
            /// </summary>
            public static string tCounter
            {
                get
                {
                    return ResourceManager.GetString("tCounter", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Desolder Cycles.
            /// </summary>
            public static string tCounterDesolCycles
            {
                get
                {
                    return ResourceManager.GetString("tCounterDesolCycles", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Hibernation Minutes.
            /// </summary>
            public static string tCounterHiber
            {
                get
                {
                    return ResourceManager.GetString("tCounterHiber", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Idle Minutes.
            /// </summary>
            public static string tCounterIdle
            {
                get
                {
                    return ResourceManager.GetString("tCounterIdle", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Plugged Minutes.
            /// </summary>
            public static string tCounterPlugged
            {
                get
                {
                    return ResourceManager.GetString("tCounterPlugged", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Counters for Station: {0}.
            /// </summary>
            public static string tCountersForStation
            {
                get
                {
                    return ResourceManager.GetString("tCountersForStation", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Sleep Minutes.
            /// </summary>
            public static string tCounterSleep
            {
                get
                {
                    return ResourceManager.GetString("tCounterSleep", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Sleep Cycles.
            /// </summary>
            public static string tCounterSleepCycles
            {
                get
                {
                    return ResourceManager.GetString("tCounterSleepCycles", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Work Minutes.
            /// </summary>
            public static string tCounterWork
            {
                get
                {
                    return ResourceManager.GetString("tCounterWork", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Port {0}.
            /// </summary>
            public static string tGlobalCounterPort
            {
                get
                {
                    return ResourceManager.GetString("tGlobalCounterPort", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Not available.
            /// </summary>
            public static string tNotAvailable
            {
                get
                {
                    return ResourceManager.GetString("tNotAvailable", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a This station do not allow partial counters..
            /// </summary>
            public static string tNotAvailableHint
            {
                get
                {
                    return ResourceManager.GetString("tNotAvailableHint", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Cannot reset protocol 01 counters..
            /// </summary>
            public static string tNotProtocol01Hint
            {
                get
                {
                    return ResourceManager.GetString("tNotProtocol01Hint", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Partial {0}.
            /// </summary>
            public static string tPartialCounterPort
            {
                get
                {
                    return ResourceManager.GetString("tPartialCounterPort", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Reset All Counters.
            /// </summary>
            public static string tResetAllCounters
            {
                get
                {
                    return ResourceManager.GetString("tResetAllCounters", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Reset Global and Partial Counters.
            /// </summary>
            public static string tResetGlobalAndPartialCountersHint
            {
                get
                {
                    return ResourceManager.GetString("tResetGlobalAndPartialCountersHint", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Reset Global Counters.
            /// </summary>
            public static string tResetGlobalCountersHint
            {
                get
                {
                    return ResourceManager.GetString("tResetGlobalCountersHint", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Reset Partial Counters.
            /// </summary>
            public static string tResetPartialCounters
            {
                get
                {
                    return ResourceManager.GetString("tResetPartialCounters", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Reset Partial counters.
            /// </summary>
            public static string tResetPartialCountersHint
            {
                get
                {
                    return ResourceManager.GetString("tResetPartialCountersHint", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Station Counters:.
            /// </summary>
            public static string tStationCounters
            {
                get
                {
                    return ResourceManager.GetString("tStationCounters", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Stations Found.
            /// </summary>
            public static string tStationsFound
            {
                get
                {
                    return ResourceManager.GetString("tStationsFound", resourceCulture);
                }
            }
        }
    }
}
