// VBConversions Note: VB project level imports
using System.Collections.Generic;
using System;
using System.Drawing;
using System.Diagnostics;
using System.Data;
using Microsoft.VisualBasic;
using System.Collections;
using System.Windows.Forms;
// End of VB project level imports

using System.Threading;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LibraryTest
{
    namespace My
    {

        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute(),
        global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0"),
        global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
        {

            private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

            #region My.Settings Auto-Save Functionality
#if _MyType
		private static bool addedHandler;
		
		private static object addedHandlerLockObject = new object();
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]private static void AutoSaveSettings(global::System.Object sender, global::System.EventArgs e)
		{
			if ((new Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase()).SaveMySettingsOnExit)
			{
				My.Settings.Default.Save();
			}
		}
#endif
            #endregion

            public static Settings Default
            {
                get
                {

#if _MyType
				if (!addedHandler)
				{
					lock(addedHandlerLockObject)
					{
						if (!addedHandler)
						{
							(new Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase()).Shutdown += AutoSaveSettings;
							addedHandler = true;
						}
					}
				}
#endif
                    return defaultInstance;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute(),
            global::System.Diagnostics.DebuggerNonUserCodeAttribute(),
            global::System.Configuration.DefaultSettingValueAttribute("02:PSE_LED_01:1234567:7654321")]
            public string updLastDataToSend
            {
                get
                {
                    return System.Convert.ToString(this["updLastDataToSend"]);
                }
                set
                {
                    this["updLastDataToSend"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute(),
            global::System.Diagnostics.DebuggerNonUserCodeAttribute(),
            global::System.Configuration.DefaultSettingValueAttribute("")]
            public string updLastProgramFile
            {
                get
                {
                    return System.Convert.ToString(this["updLastProgramFile"]);
                }
                set
                {
                    this["updLastProgramFile"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute(),
            global::System.Diagnostics.DebuggerNonUserCodeAttribute(),
            global::System.Configuration.DefaultSettingValueAttribute("True")]
            public bool UpgradeSettings
            {
                get
                {
                    return System.Convert.ToBoolean(this["UpgradeSettings"]);
                }
                set
                {
                    this["UpgradeSettings"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute(),
            global::System.Diagnostics.DebuggerNonUserCodeAttribute(),
            global::System.Configuration.DefaultSettingValueAttribute("")]
            public string filesLastPathFile
            {
                get
                {
                    return System.Convert.ToString(this["filesLastPathFile"]);
                }
                set
                {
                    this["filesLastPathFile"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute(),
            global::System.Diagnostics.DebuggerNonUserCodeAttribute(),
            global::System.Configuration.DefaultSettingValueAttribute("500000")]
            public string serialPort_Baudios
            {
                get
                {
                    return System.Convert.ToString(this["serialPort_Baudios"]);
                }
                set
                {
                    this["serialPort_Baudios"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute(),
            global::System.Diagnostics.DebuggerNonUserCodeAttribute(),
            global::System.Configuration.DefaultSettingValueAttribute("8")]
            public string serialPort_DataBits
            {
                get
                {
                    return System.Convert.ToString(this["serialPort_DataBits"]);
                }
                set
                {
                    this["serialPort_DataBits"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute(),
            global::System.Diagnostics.DebuggerNonUserCodeAttribute(),
            global::System.Configuration.DefaultSettingValueAttribute("Even")]
            public string serialPort_Parity
            {
                get
                {
                    return System.Convert.ToString(this["serialPort_Parity"]);
                }
                set
                {
                    this["serialPort_Parity"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute(),
            global::System.Diagnostics.DebuggerNonUserCodeAttribute(),
            global::System.Configuration.DefaultSettingValueAttribute("One")]
            public string serialPort_StopBits
            {
                get
                {
                    return System.Convert.ToString(this["serialPort_StopBits"]);
                }
                set
                {
                    this["serialPort_StopBits"] = value;
                }
            }
        }
    }

    namespace My
    {

        [global::Microsoft.VisualBasic.HideModuleNameAttribute(),
        global::System.Diagnostics.DebuggerNonUserCodeAttribute(),
        global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        internal sealed class MySettingsProperty
        {

            [global::System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")]
            internal static My.Settings Settings
            {
                get
                {
                    return My.Settings.Default;
                }
            }
        }
    }
}
