//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace JBCTraceControlLocalSrv
{
    namespace My.Resources
    {
        using System;


        /// <summary>
        ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
        /// </summary>
        // StronglyTypedResourceBuilder generó automáticamente esta clase
        // a través de una herramienta como ResGen o Visual Studio.
        // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
        // con la opción /str o recompile su proyecto de VS.
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]

        public class Resources
        {

            private static global::System.Resources.ResourceManager resourceMan;

            private static global::System.Globalization.CultureInfo resourceCulture;

            [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
            internal Resources()
            {
            }

            /// <summary>
            ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
            /// </summary>
            [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
            public static global::System.Resources.ResourceManager ResourceManager
            {
                get
                {
                    if (object.ReferenceEquals(resourceMan, null))
                    {
                        global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("My.Resources.Resources", typeof(Resources).Assembly);
                        resourceMan = temp;
                    }
                    return resourceMan;
                }
            }

            /// <summary>
            ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
            ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
            /// </summary>
            [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
            public static global::System.Globalization.CultureInfo Culture
            {
                get
                {
                    return resourceCulture;
                }
                set
                {
                    resourceCulture = value;
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Function not supported.
            /// </summary>
            public static string errFunctionNotSupported
            {
                get
                {
                    return ResourceManager.GetString("errFunctionNotSupported", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Not controlled error. See Detail data..
            /// </summary>
            public static string errNotControlled
            {
                get
                {
                    return ResourceManager.GetString("errNotControlled", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Not valid tool..
            /// </summary>
            public static string errNotValidTool
            {
                get
                {
                    return ResourceManager.GetString("errNotValidTool", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Error in service. See Detail data..
            /// </summary>
            public static string errServiceError
            {
                get
                {
                    return ResourceManager.GetString("errServiceError", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Station not found..
            /// </summary>
            public static string errStationNotFound
            {
                get
                {
                    return ResourceManager.GetString("errStationNotFound", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Error creating service.
            /// </summary>
            public static string evErrorCreating
            {
                get
                {
                    return ResourceManager.GetString("evErrorCreating", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Custom Command Error.
            /// </summary>
            public static string evErrorOnCustomCommand
            {
                get
                {
                    return ResourceManager.GetString("evErrorOnCustomCommand", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Error starting JBC Connect DLL.
            /// </summary>
            public static string evErrorStartingDLL
            {
                get
                {
                    return ResourceManager.GetString("evErrorStartingDLL", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a New Event Service.
            /// </summary>
            public static string evNew
            {
                get
                {
                    return ResourceManager.GetString("evNew", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Off.
            /// </summary>
            public static string evOff
            {
                get
                {
                    return ResourceManager.GetString("evOff", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a On.
            /// </summary>
            public static string evOn
            {
                get
                {
                    return ResourceManager.GetString("evOn", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Searching Ethernet Stations.
            /// </summary>
            public static string evSearchingETHStations
            {
                get
                {
                    return ResourceManager.GetString("evSearchingETHStations", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Not Searching Stations.
            /// </summary>
            public static string evSearchingNone
            {
                get
                {
                    return ResourceManager.GetString("evSearchingNone", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Searching USB Stations.
            /// </summary>
            public static string evSearchingUSBStations
            {
                get
                {
                    return ResourceManager.GetString("evSearchingUSBStations", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Searching ETH Setting: {0}.
            /// </summary>
            public static string evSetSearchingETH
            {
                get
                {
                    return ResourceManager.GetString("evSetSearchingETH", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Searching USB Setting: {0}.
            /// </summary>
            public static string evSetSearchingUSB
            {
                get
                {
                    return ResourceManager.GetString("evSetSearchingUSB", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Service Started.
            /// </summary>
            public static string evStarted
            {
                get
                {
                    return ResourceManager.GetString("evStarted", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Starting....
            /// </summary>
            public static string evStarting
            {
                get
                {
                    return ResourceManager.GetString("evStarting", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Service Stopped.
            /// </summary>
            public static string evStopped
            {
                get
                {
                    return ResourceManager.GetString("evStopped", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Stopping....
            /// </summary>
            public static string evStopping
            {
                get
                {
                    return ResourceManager.GetString("evStopping", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Stop Searching Ethernet Stations.
            /// </summary>
            public static string evStopSearchingETHStations
            {
                get
                {
                    return ResourceManager.GetString("evStopSearchingETHStations", resourceCulture);
                }
            }

            /// <summary>
            ///   Busca una cadena traducida similar a Stop Searching USB Stations.
            /// </summary>
            public static string evStopSearchingUSBStations
            {
                get
                {
                    return ResourceManager.GetString("evStopSearchingUSBStations", resourceCulture);
                }
            }
        }
    }
}
